### ISSUE TITLE
Ability to Have Popups on Close-Up Map.

### ISSUE THREAD

**Issue by mngisguy** [Esri/countdown-storytelling-template-js#13]
Is this possible as of yet?  It sure would be helpful!

**Comment by ssylvia** [comment]
The template is no longer in active development. A new updated compare app can be found here: http://www.arcgis.com/home/item.html?id=051252bd1a5a4a8c9cba099f8bf59d8e. The repo is available here: https://github.com/Esri/Compare-Maps-Template
