### ISSUE TITLE
On Chrome: at some web browser widths the map in some Countdowns doesn't draw correctly

### ISSUE THREAD

**Issue by RupertEssinger** [Esri/countdown-storytelling-template-js#14]
On Chrome (testing on Windows) I noticed that the map in some Countdowns doesn't completely fill the available display, either when I first open it or if I press Refresh. I can repro it with these:

http://geoweb.cityofsalem.net/storymaps/city_projects/index_noiebypass.html
http://f1map.herokuapp.com/
http://tplgis.org/storymaps/GreenMountains/index.html
http://www.esrimaps.cl/playas/index.html

at window size 1377x895

It's not an issue for all Countdowns. For example I can't repro it with:
http://www.iowadot.gov/roadconstruction/2015Projects/index.html

**Comment by leebock** [comment]
fixed https://github.com/leebock/countdown-storytelling-template-js/commit/f8d028e0047650a5180d41bb4bfefd8278389091
